CONFIG_ZMK_BLE=y

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n 

CONFIG_PMW3610=y
CONFIG_PMW3610_SWAP_XY=y
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_INVERT_Y=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y